on:
  push:
    branches:
      - master

jobs:
  clojars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: "1.10.1.469"
      - run:
          clojure -Sdeps '{:deps {olical/depot {:mvn/version "1.8.4"}}}' -m
          depot.outdated.main
